[demarc:syslog]
shouldLine = false
timePrefix = ^
timeFormat = YYYY-MM-DD HH:mm:ss
dateTime = AUTO
maximum_lookHead = 15
lineBreaker = newline
truncate = 10000
TRANSFORMS-set_host = demarc-host-transform
